### ISSUE TITLE
Feedback for “Interact with your Tokenbound Account (TBA) on local blockchain using nodejs”

### ISSUE THREAD

**Issue by lc1993929** [tokenbound/docs#34]
Transfer ETH from the TBA to your wallet

the TBA is queried from registry contract.So ,can anyone query the TBA account from registry contract?
And I don't find any auth-check in (Transfer ETH from the TBA to your wallet),
![image](https://github.com/tokenbound/docs/assets/24772267/f596c2f9-e83f-4add-8586-cc558be868d2)

Whether anyone can initiate a transfer as long as they have the TBA?

Thanks for answering

**Comment by anggxyz** [comment]
Hey @lc1993929! 👋🏽 

Only the owner of the NFT on the chain should be able to execute the transaction. The function would revert if a non-owner calls it

**Comment by lc1993929** [comment]
> Hey @lc1993929! 👋🏽
> 
> Only the owner of the NFT on the chain should be able to execute the transaction. The function would revert if a non-owner calls it

ok,thank you
