### ISSUE TITLE
broken url

### ISSUE THREAD

**Issue by jacmos3** [tokenbound/docs#38]
Hello, the polygon button which links to opensea in the tokenbound website, is broken because 

it links to:
https: // opensea.io/assets/**polygon**/[address]/[tokenid]

instead of:
https: // opensea.io/assets/**matic**/[address]/[tokenid]

thanks

**Comment by bjfresh** [comment]
@jacmos3 this is in the works, too... it's a little tricky and we'll want to be careful with it because it gets down into the plumbing a little bit, but a fix should be out soon!
