### ISSUE TITLE
WearablePack

### ISSUE THREAD

**Issue by k1ic** [tokenbound/docs#40]
Use ERC-6551 to package and sell Wearables in Metaverse. 
Website: https://wearable-pack.vercel.app/
![image](https://github.com/tokenbound/docs/assets/5465932/de00309e-789a-4455-8e19-df81695bb90f)
![image](https://github.com/tokenbound/docs/assets/5465932/0c38fd8e-ce3c-4238-b484-51880f29050a)
![image](https://github.com/tokenbound/docs/assets/5465932/6264d25f-0799-4449-ad93-1e625dfaaacc)
![image](https://github.com/tokenbound/docs/assets/5465932/9e1b756a-7721-4bce-b2c6-bcd4a19db387)

**Comment by bjfresh** [comment]
@k1ic thanks for sharing! The best place to get feedback from others in the community would be the working group Telegram: https://t.me/tokenbound
