### ISSUE TITLE
Showcase Request: Hood Rats NFT Collection - Tokenbound Accounts Integration

### ISSUE THREAD

**Issue by Jharmony** [tokenbound/docs#51]
# Project Overview:

## Hood Rats NFT Collection:
Hood Rats is a vibrant NFT collection, drawing inspiration from classic Anime and fictional universes like Star Wars. Featuring 10,000 unique items, each NFT incorporates elements from beloved animes such as Dragon Ball and Jojo's Bizarre Adventure.

### Iframe Implementation: 
We have seamlessly integrated Tokenbound's open-source iframe into our 10,000-item collection, enhancing user experience and interaction.

### Permanent Data Storage: 
Our collection's metadata and art are securely stored on Arweave, courtesy of ArDrive. This ensures the long-term preservation of our NFT data, safeguarding our artistic vision for future generations.

### ArDrive Spotlight: 
Our collection, securely stored on Arweave by ArDrive, takes center stage in an article at [https://ardrive.io/hood-rats](https://ardrive.io/hood-rats), celebrating the artistic diversity, while delving into the founder's journey and the innovative use of decentralized storage for long-term preservation.

### Art Generator 2.0 by Hashlips: 
We utilized the latest Art Generator 2.0 by Hashlips to craft visually stunning and diverse NFTs, adding a unique touch to each piece in our collection.

### ERC6551 Standard: 
Leveraging the SDK from tokenbound.org, we actively explore opportunities to build with the new ERC6551 standard. This innovation allows each digital collectible in our collection to have its unique address on the Ethereum network, unlocking limitless possibilities for creativity and functionality.

### Educational Initiatives: 
Within our community Discord, we host educational sessions covering Web3, open-source initiatives, and programming. These sessions aim to empower our community members with knowledge and skills in the rapidly evolving blockchain space.

### Minting DApp: 
Explore our user-friendly minting DApp to create and collect Hood Rats NFTs effortlessly. [Minting Dapp](https://hoodrats.ar-io.dev/) [Alt Dapp](https://mint_hoodrats.ar-io.dev)

### OpenSea Page: 
Visit our OpenSea page to view and acquire Hood Rats NFTs. [OpenSea](https://opensea.io/collection/hood-rats)

### Twitter Account: 
Follow us on X for the latest updates and announcements. [X Official](https://twitter.com/HoodRatNFTs)

### Discord Community: 
Join our vibrant Discord community to engage with fellow collectors and enthusiasts. [Discord Community](https://discord.gg/8NprDwRf2n)

### Bilingual Twitter Spaces Community: 
Participate in our active bilingual Twitter Spaces community, La Barberia Web3, directly connected to our NFT collection. Engage in discussions, share insights, and connect with other enthusiasts in both English and Spanish.

### Our project exemplifies Tokenbound Accounts's capabilities, showcasing your technology's power in enhancing the NFT ecosystem. We would like to be featured in your showcase, allowing us to share our story and inspire fellow developers and creators in the Web3 space.

Thank you for your time and consideration.

## Contact Information:

Name: Hood Rats NFTs
Email: hoodratnfts@gmail.com
GitHub Username: Jharmony

![123123](https://github.com/tokenbound/docs/assets/22645740/04570f18-0e23-49fd-909e-ca1631678a83)

**Comment by bjfresh** [comment]
@Jharmony feel free to submit a PR to this repo adding Hood Rats to the showcase.

**Comment by Jharmony** [comment]
The PR has been submitted. Thanks in advance.
