### ISSUE TITLE
Add STP to Project Showcase

### ISSUE THREAD

**Issue by wy2358** [tokenbound/docs#52]
STP is opening the portal to Autonomous Worlds. We aim to provide the necessary infrastructure, tooling platforms and data indexing for elevated forms of on-chain identity. As our first product into the AW ecosystem, we are building AWNS, short for AW Naming Service. AWNS implements the unique domain extension .AW, but is also an account powered by ERC-6551. 

AWNS leverages ERC-6551 so that:
- You can seamlessly connect AWNS to any AW app and game in our ecosystem.
- You can earn experiences & badges in-game that are natively attached to the AWNS in provenance and history.
- Your decisions are recorded to create new paths, abilities are acquired to unlock new assets, and more boundless game use-cases are enabled.
- In-app and game data usage will cultivate your identity and social profile visible for open interaction and collaboration.

Contact info and links: 
contact@stp.network
stp.network/awns

**Comment by bjfresh** [comment]
@wy2358 feel free to submit a PR to this repo + add a showcase when the project is ready for public consumption.
