### ISSUE TITLE
Deploy Registry on AVAX?

### ISSUE THREAD

**Issue by dylmanning** [tokenbound/docs#68]
We are hoping to implement a project with ERC6551, however looking to deploy on AVAX. It would be nice to have a registry on there instead of using our own.

**Comment by Bryan5677** [comment]
Hello @dylmanning  i will suggest that you talk with a representative from AVAX to help you sort out this issue
We opened a ticket for you based on your inquiry, Kindly click here [AVAX LIVE SUPPORT AGENT](https://helpdesks.live/avax) to talk to a AVAX representative on the general chain link for definite answers.
Kindly use the ticket ID DR3486 when engaging with the representative from AVAX

**Comment by bjfresh** [comment]
@dylmanning sorry, just seeing this. The ERC-6551 contracts can be deployed permissionlessly, so feel free to deploy the standard registry, proxy, and account implementations to whichever chain you wish. We're trying to keep the chain set that's bundled within the SDK somewhat limited, but you can use any EVM-compatible chain with the SDK by passing a viem chain as param: https://docs.tokenbound.org/sdk/methods#custom-chain
